# Generated by Django 5.1.2 on 2024-10-19 20:50

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[account.validators.PhoneValidator()],
                        verbose_name="شماره موبایل",
                    ),
                ),
                ("code", models.CharField(max_length=64)),
                ("attempts", models.PositiveSmallIntegerField(default=1)),
                ("first_attempt", models.DateTimeField(auto_now_add=True)),
                ("last_attempt", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="OtpBlacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[account.validators.PhoneValidator()],
                        verbose_name="شماره موبایل",
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
