# Generated by Django 5.1.2 on 2024-10-22 21:01

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_otp_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpblacklist",
            name="phone",
            field=models.CharField(
                max_length=11,
                validators=[account.validators.PhoneValidator()],
                verbose_name="شماره موبایل",
            ),
        ),
    ]
