# Generated by Django 5.1.2 on 2024-10-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_otpblacklist_phone"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(fields=["phone"], name="authenticat_phone_19fdbb_idx"),
        ),
        migrations.AddIndex(
            model_name="otpblacklist",
            index=models.Index(fields=["phone"], name="authenticat_phone_a2b438_idx"),
        ),
    ]
