# Generated by Django 4.2.13 on 2024-07-07 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_code', models.CharField(max_length=50, unique=True)),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_insurances', to='medical.insurance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_insurances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'insurance_code')},
            },
        ),
    ]
