# Generated by Django 4.2.13 on 2024-07-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created',
        ),
        migrations.RemoveField(
            model_name='province',
            name='created',
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
