# Generated by Django 4.2.13 on 2024-07-07 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medical.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0003_remove_city_created_remove_province_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('introduction', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/images/medical')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_centers', to='medical.city')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_centers', to='medical.facility')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_centers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCenterStatus',
            fields=[
                ('medical_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='medical.medicalcenter')),
                ('approval_status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('suspended', 'معلق شده'), ('archived', 'بایگانی شده')], default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCenterGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='uploads/images/medical')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='medical.medicalcenter')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCenterAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=500)),
                ('medical_center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='medical.medicalcenter')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCenterTelephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, validators=[medical.validators.TelephoneValidator()])),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='medical.medicalcenter')),
            ],
            options={
                'unique_together': {('medical_center', 'telephone')},
            },
        ),
        migrations.CreateModel(
            name='MedicalCenterSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(5, 'شنبه'), (6, 'یکشنبه'), (0, 'دوشنبه'), (1, 'سه\u200cشنبه'), (2, 'چهارشنبه'), (3, 'پنج\u200cشنبه'), (4, 'جمعه')])),
                ('open_at', models.TimeField()),
                ('close_at', models.TimeField()),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='medical.medicalcenter')),
            ],
            options={
                'unique_together': {('medical_center', 'day')},
            },
        ),
    ]
