# Generated by Django 4.2.13 on 2024-07-07 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medical.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0004_facility_medicalcenter_medicalcenterstatus_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinsurance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalcenter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/medical/images'),
        ),
        migrations.AlterField(
            model_name='medicalcentergallery',
            name='photo',
            field=models.ImageField(upload_to='uploads/medical/images'),
        ),
        migrations.AlterField(
            model_name='province',
            name='image',
            field=models.ImageField(upload_to='uploads/medical/images', validators=[medical.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='province',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurances', to='medical.insurance'),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='insurance_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to=settings.AUTH_USER_MODEL),
        ),
    ]
