# Generated by Django 4.2.13 on 2024-07-08 13:27

from django.db import migrations, models
import django.db.models.deletion
import doctor.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_user_options_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='specialization/images', validators=[doctor.validators.validate_image_svg])),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctor/avatars', validators=[doctor.validators.validate_image_jpg_jpeg])),
                ('appointment_gap', models.DurationField()),
                ('medical_system_number', models.CharField(max_length=10)),
                ('appointment_fee', models.IntegerField()),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='doctor.doctordegree')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='account.profile')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='doctor.specialization')),
            ],
        ),
    ]
