# Generated by Django 4.2.13 on 2024-07-10 19:37

from django.db import migrations, models
import django.db.models.deletion
import doctor.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_alter_user_role'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='specialization/images', validators=[doctor.validators.validate_image_svg])),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='doctor/avatars', validators=[doctor.validators.validate_image_jpg_jpeg])),
                ('appointment_gap', models.DurationField()),
                ('medical_system_number', models.CharField(max_length=10)),
                ('appointment_fee', models.IntegerField()),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='doctor.doctordegree')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='account.profile')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='doctor.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(5, 'شنبه'), (6, 'یکشنبه'), (0, 'دوشنبه'), (1, 'سه\u200cشنبه'), (2, 'چهارشنبه'), (3, 'پنج\u200cشنبه'), (4, 'جمعه')])),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='doctor.doctor')),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='medical.medicalcenter')),
            ],
            options={
                'unique_together': {('doctor', 'medical_center', 'day')},
            },
        ),
    ]
