# Generated by Django 4.2.13 on 2024-07-08 13:35

from django.db import migrations, models
import doctor.validators


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='image',
            field=models.FileField(upload_to='specialization/images', validators=[doctor.validators.validate_image_svg]),
        ),
    ]
