# Generated by Django 4.2.13 on 2024-07-10 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='medical_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='medical.medicalcenter'),
        ),
    ]
