# Generated by Django 4.2.13 on 2024-09-28 20:26

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("nation_code", models.CharField(max_length=10, unique=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "آقا"), ("female", "خانم")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[account.validators.PhoneValidator()],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "ادمین"),
                            ("manager", "مدیر"),
                            ("doctor", "دکتر"),
                            ("patient", "بیمار"),
                        ],
                        default="patient",
                        max_length=10,
                        verbose_name="نقش",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ عضویت"),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
    ]
