# Generated by Django 4.2.13 on 2024-07-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_options_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/account/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ادمین'), ('manager', 'مدیر'), ('doctor', 'دکتر'), ('patient', 'بیمار')], default='patient', max_length=10, verbose_name='نقش'),
        ),
    ]
